spring.application.name=booking-service
spring.data.mongodb.uri=mongodb://localhost:27017/smartcampus
server.port=8081

spring.security.oauth2.client.registration.google.client-id=876930232911-far5j5l3orgboutjgbla3kmoj1k156g3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile